// POST 
export const SET_POST_DETAILS = 'SET_POST_DETAILS';

// TEST POST 
export const TEST_POST_GET = 'TEST_POST_GET';
//USER INFO
export const SET_USER_INFO = 'SET_USER_INFO';
//NAVIGATION 
export const SET_PAGE = 'SET_PAGE';
//SCROLLING
export const SET_SCROLLING = 'SET_SCROLLING';
//FULL SCREEN IMAGE
export const SET_FULL_SCREEN_IMAGE = 'SET_FULL_SCREEN_IMAGE';